services:
  ubuntu-noble-novnc:
    container_name: ubuntu-noble-novnc
    image: cire21st/ubuntu-noble-full:latest
    privileged: true
    ipc: host
    pid: host
    ports:
      - 80:80
    volumes:
      - ./workspace:/home/ubuntu/Desktop
    stdin_open: true
    tty: true
    platform: linux/amd64
